version: "3.8"
services:
  littlehorse:
    image: ghcr.io/littlehorse-enterprises/littlehorse/lh-standalone:0.7.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://littlehorse:1822/liveness"]
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - 2023:2023
      - 8080:8080
    environment:
      - LHS_ADVERTISED_LISTENERS=external://localhost:2023
  
  database:
    image: postgres:16
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
