spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ledger}
  jpa:
    show-sql: true
    database: postgresql

server:
  port: ${PORT:8081}

worker: ${WORKER:warehouse}
register-workflow: ${REGISTER_WORKFLOW:false}
notifications-service: ${NOTIFICATIONS_SERVICE:http://localhost:3001}
