/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lh.demo.it.request.wf;

import io.littlehorse.sdk.common.config.LHConfig;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        // This loads configuration from environment variables. If no config is present
        // in the environment variables, the defaults will point you to localhost, which
        // is where the quickstart `lh-standalone` container runs.
        LHConfig config = new LHConfig();

        ITRequestWorkflow workflow = new ITRequestWorkflow(config);
        workflow.registerWorkflowSpec();
    }
}
