INSERT INTO products (id, name, description, price, stock, category) VALUES (1, 'Laptop', 'High performance laptop with SSD', 999.99, 50, 'Electronics');
INSERT INTO products (id, name, description, price, stock, category) VALUES (2, 'Smartphone', 'Latest model with high resolution camera', 699.99, 100, 'Electronics');
INSERT INTO products (id, name, description, price, stock, category) VALUES (3, 'Desk Chair', 'Ergonomic office chair', 199.99, 30, 'Furniture');
INSERT INTO products (id, name, description, price, stock, category) VALUES (4, 'Coffee Table', 'Modern design coffee table', 149.99, 20, 'Furniture');
INSERT INTO products (id, name, description, price, stock, category) VALUES (5, 'T-Shirt', 'Cotton t-shirt, various colors', 19.99, 200, 'Clothing');
INSERT INTO products (id, name, description, price, stock, category) VALUES (6, 'Jeans', 'Classic fit denim jeans', 49.99, 150, 'Clothing');
INSERT INTO products (id, name, description, price, stock, category) VALUES (7, 'Bluetooth Speaker', 'Portable wireless speaker', 79.99, 80, 'Electronics');
INSERT INTO products (id, name, description, price, stock, category) VALUES (8, 'Headphones', 'Noise cancelling over-ear headphones', 149.99, 60, 'Electronics');
INSERT INTO products (id, name, description, price, stock, category) VALUES (9, 'Book Shelf', 'Wooden shelf for books and decoration', 89.99, 40, 'Furniture');
INSERT INTO products (id, name, description, price, stock, category) VALUES (10, 'Backpack', 'Water resistant backpack', 39.99, 120, 'Accessories');
